# Generated by Django 5.1.1 on 2024-10-04 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='id',
            field=models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
