# Generated by Django 5.1.1 on 2024-10-04 18:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0003_alter_application_id_alter_seminar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='id',
            field=models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
